---
- name: create users based on list
  hosts: localhost
  gather_facts: false
  vars:
    users:
      - name: Bach
        first: Johann
        middle: Sebastian
        uid: 2001
      - name: Mozart
        first: Wolfgang
        middle: Amadeus
        uid: 2002
      - name: Haydn
        first: Franz
        middle: Joseph
        uid: 2003

  tasks:
    - name: create PW files
      vars:
        ## reference: https://docs.ansible.com/ansible/2.9/plugins/lookup/password.html
        password: "{{ lookup('password', '/dev/null length=6 chars=digits') }}"
        ##reference: https://docs.ansible.com/ansible/2.9/user_guide/playbooks_filters.html#hashing-filters
        ##reference: https://ansibledaily.com/idempotent-random-number/
        salt: "{{ 65534 | random(seed=inventory_hostname) | string }}"
      template:
        src: password_file_template.j2 
        dest: "credentials/password-{{ item.name | lower }}"
      loop: "{{ users }}"
      tags:
        - never
        - password

    - name: debug variable
      vars:
        credentials: "{{ query('lines', 'cat credentials/password-' + item.name | lower) }}"
      debug:
        msg: 
          - "split password is: {{ credentials[0].split()[1] }}"
          - "split salt is: {{ credentials[1].split()[1] }}"
          - "replace password is: {{ credentials[0] | replace('password: ', '') }}"
          - "replace salt is: {{ credentials[1] | replace('salt: ', '') }}"
      loop: "{{ users }}"
      tags:
        - never
        - debug

    - name: create users
      vars:
        credentials: "{{ query('lines', 'cat credentials/password-' + item.name | lower) }}"
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        comment: "{{ item.first }} {{ item.middle }} {{ item.name }}"
        password: "{{ credentials[0].split()[1] | password_hash('sha512', credentials[1].split()[1]) }}"
        update_password: on_create
        state: present
      loop: "{{ users }}"
      become: true
      tags:
        - never
        - user
