---
- name: test transforming txt file content to list for processing
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - filelist
  tasks:

    - name: load text from file and transform it
      vars:
        my_txt: "{{ lookup('file', item).split() }}"
        my_ips: "{{ lookup('file', item) }}"
        my_ips1: "{{ lookup('template', 'temp_template.j2').split() | ipaddr | unique }}"
        my_ips2: "{{ my_ips1 | default('no IP found', true) }}"
      debug:
        msg:
          - "{{ my_ips }}"
          - "{{ my_ips1 }}"
          - "{{ lookup('template', 'ip_template_v2.j2') }}"
      loop: "{{ files }}"

    - name: load text from file and transform it and write to file
      vars:
        my_ips: "{{ lookup('file', item).split() | ipv4 | unique }}"
      template:
        src: "ip_template.j2"
        dest: "{{ item }}.ip"
      loop: "{{ files }}"
      ## use loop: "{{ query('lines', 'cat fileslist') }}" if vars_files can not be used
      ## could also use copy module with content: "{{ lookup('template', 'ip_template_v2.j2') }}"
      ## alternatives to split strings:
      ## my_list="{{ (myString | regex_replace(':|.', ':')).split(':') }}"
      ## mystr="{{ myString | regex_findall('([^:.]+)') }} "
